chromiumDev: Fix the build (libxshmfence is now required)
Error:
../../components/viz/service/display_embedder/output_presenter_x11.cc:8:10:
fatal error: 'X11/xshmfence.h' file not found
         ^~~~~~~~~~~~~~~~~
1 error generated.

(cherry picked from commit 351f3c043d80009569d646a332025f7870b11cf3)